DROP TABLE IF EXISTS `opt_signin_record`;
CREATE TABLE IF NOT EXISTS `opt_signin_record` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `delflag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除标示',
  `createAt` bigint(20) NOT NULL DEFAULT '0' COMMENT '数据创建时间戳',
  `updateAt` bigint(20) NOT NULL DEFAULT '0' COMMENT '数据更新时间戳',
  `month` int(11) NOT NULL,
  `year` int(11) NOT NULL,
  `uid` varchar(50) NOT NULL,
  `d1` tinyint(1) NOT NULL DEFAULT '0',
  `d2` tinyint(1) NOT NULL DEFAULT '0',
  `d3` tinyint(4) NOT NULL DEFAULT '0',
  `d4` tinyint(4) NOT NULL DEFAULT '0',
  `d5` tinyint(4) NOT NULL DEFAULT '0',
  `d6` tinyint(4) NOT NULL DEFAULT '0',
  `d7` tinyint(4) NOT NULL DEFAULT '0',
  `d8` tinyint(4) NOT NULL DEFAULT '0',
  `d9` tinyint(4) NOT NULL DEFAULT '0',
  `d10` tinyint(4) NOT NULL DEFAULT '0',
  `d11` tinyint(4) NOT NULL DEFAULT '0',
  `d12` tinyint(4) NOT NULL DEFAULT '0',
  `d13` tinyint(4) NOT NULL DEFAULT '0',
  `d14` tinyint(4) NOT NULL DEFAULT '0',
  `d15` tinyint(4) NOT NULL DEFAULT '0',
  `d16` tinyint(4) NOT NULL DEFAULT '0',
  `d17` tinyint(4) NOT NULL DEFAULT '0',
  `d18` tinyint(4) NOT NULL DEFAULT '0',
  `d19` tinyint(4) NOT NULL DEFAULT '0',
  `d21` tinyint(4) NOT NULL DEFAULT '0',
  `d22` tinyint(4) NOT NULL DEFAULT '0',
  `d23` tinyint(4) NOT NULL DEFAULT '0',
  `d24` tinyint(4) NOT NULL DEFAULT '0',
  `d25` tinyint(4) NOT NULL DEFAULT '0',
  `d26` tinyint(4) NOT NULL DEFAULT '0',
  `d27` tinyint(4) NOT NULL DEFAULT '0',
  `d28` tinyint(4) NOT NULL DEFAULT '0',
  `d29` tinyint(4) NOT NULL DEFAULT '0',
  `d30` tinyint(4) NOT NULL DEFAULT '0',
  `d31` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='签到表';